cars
names(cars)
plot(speed~dist,cars)
plot(dist~speed,cars,lab=c(20,10,5))
plot(cars, lab=c(20,10,6), cex.axis=.9)
plot(cars, lab=c(20,10,6), cex.axis=.6, las=1)
points(x=c(23,22) ,y=c(60,61) ,col ="green")
plot(cars, lab=c(20,10,6), cex.axis=.6, las=1,xlim=c(4,26))
points(x=c(23,26) ,y=c(60,61) ,col ="green")
plot(cars, lab=c(20,10,6), cex.axis=.6, las=1, xlim=c(4,26))
points(x=c(23,26), y=c(60,61), col="red")
abline(a=-17.5, b=3.93, col="blue", lty=2)
#lty =linetype:
plot(cars, lab=c(20,10,6), cex.axis=.6, las=1, xlim=c(4,26))
points(x=c(23,26), y=c(60,61), col="red")
abline(a=-17.5, b=3.93, col="blue", lty=2)
title(expression(paste("Regression : ",beta[0], "= -17.5, ", beta[1], "= -3.93")))

plot(cars, lab=c(20,10,6), cex.axis=.6, las=1, xlim=c(4,26))
points(x=c(23,26), y=c(60,61), col="red")
legend(7,100,c("OLD","NEW"),col=c("black","red"),pch =1)
par(mfrow(1,2))
hist(cars[,1] ,,main="Speed")
hist(cars[,2],main="Distance")

par(mfrow=c(1,3))
hist(cars[,2], main="Distance histogram", xlab="Distance")
hist(cars[,1], main="Speed histogram", xlab="Speed")
hist(cars[,2], main="Distance histogram", xlab="Distance")
layout(matrix(c(1,1,2,3,4,5), ncol=3))
plot(cars,main="Scatter Plot", las=1)
hist(cars[,1], main="Speed histogram", xlab="Speed")
hist(cars[,2], main="Distance histogram", xlab="Distance")
hist(cars[,1], main="Speed histogram", xlab="Speed")
hist(cars[,2], main="Distance histogram", xlab="Distance")
